name: update_xray_json_config_for_dig
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: update_xray_json_config_for_dig
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rm -rf xray_json_config_for_dig
          git clone git@github.com:shoguncao/xray_json_config_for_dig.git
          pushd xray_json_config_for_dig
          ./delete_unavailable_json_cfg.sh
          ./add_link_2_json_cfg.sh
          popd xray_json_config_for_dig
